export const database = {
  games: [
    {
      id: 1,
      name: 'Last Of Us Part 1',
      category: 'adventure',
      thumbnail: './assets/images/lastcard.jpg',
      image: './assets/images/last.jpg',
      video: 'https://www.youtube.com/embed/LW5NwaUXgIA',
      description:
        'Experience the emotional storytelling and unforgettable characters in The Last of Us™, winner of over 200 Game of the Year awards. In a ravaged civilization, where infected and hardened survivors run rampant, Joel, a weary protagonist, is hired to smuggle 14-year-old Ellie out of a military quarantine zone. However, what starts as a small job soon transforms into a brutal cross-country journey.',
      screenshot1: './assets/images/lastshot.jpg',
      buy: 'Buy Last Of Us Part 1',
      price: '₹ 3,999',
      des: 'Includes the complete The Last of Us single-player story and celebrated prequel chapter, Left Behind, which explores the events that changed the lives of Ellie and her best friend Riley forever.',
      bit: 'Requires a 64-bit processor and operating system',
      os: 'OS: Windows 10 (Version 1909 or Newer)',
      processor: 'Processor: AMD Ryzen 5 1500X, Intel Core i7-4770K',
      memory: 'Memory: 16 GB RAM',
      graphics:
        'Graphics: AMD Radeon RX 470 (4 GB), AMD Radeon RX 6500 XT (4 GB), NVIDIA GeForce GTX 970 (4 GB), NVIDIA GeForce 1050 Ti (4 GB)',
      storage: 'Storage: 100 GB available space',
      notes: 'Additional Notes: SSD Recommended',
      bit1: 'Requires a 64-bit processor and operating system',
      os1: 'OS: Windows 10 (Version 1909 or Newer)',
      processor1: 'Processor: AMD Ryzen 5 3600X, Intel Core i7-8700',
      memory1: 'Memory: 16 GB RAM',
      graphics1:
        'Graphics: AMD Radeon RX 5700 XT (8 GB), AMD Radeon RX 6600 XT (8 GB), NVIDIA GeForce RTX 2070 SUPER (8 GB), NVIDIA GeForce RTX 3060 (8 GB)',
      storage1: 'Storage: 100 GB available space',
      notes1: 'Additional Notes: SSD Recommended',
      trending: true,
    },
    {
      id: 2,
      name: 'Uncharted Legacy Of Thieves',
      category: 'adventure',
      thumbnail: './assets/images/unchartedcard.jpg',
      image: './assets/images/uncharted.jpg',
      video: 'https://www.youtube.com/embed/xeMA3O9pfiY',
      description:
        'Are You Ready To Seek Your Fortune? Seek your fortune and leave your mark on the map in the UNCHARTED: Legacy of Thieves Collection. Uncover the thrilling cinematic storytelling and the largest blockbuster action set pieces in the UNCHARTED franchise, packed with all the wit, cunning, and over the top moments of the beloved thieves – Nathan Drake and Chloe Frazer.In an experience delivered by award winning developer Naughty Dog, the UNCHARTED: Legacy of Thieves Collection includes the two critically-acclaimed, globe-trotting single player adventures from UNCHARTED™ 4: A Thief’s End and UNCHARTED™: The Lost Legacy. Each story is filled with laughs, drama, high octane combat, and a sense of wonder – remastered to be even more immersive.',
      screenshot1: './assets/images/unchartedshot.jpg',
      buy: 'Buy Uncharted Legacy of Thieves',
      des: 'From thick jungles to snow-capped mountains, exotic islands to rain-soaked streets, explore every inch of stunningly beautiful environments in spectacular detail. Immerse yourself in the cinematic storytelling with super-sharp 4K resolution*, and Ultra-Wide Monitor support**. Enjoy a host of enhanced graphical adjustment features such as adjustable Texture and Model Quality, Anisotropic Filtering, Shadows, Reflections and Ambient Occlusion.',
      price: '₹ 3,299',
      bit: 'Requires a 64-bit processor and operating system',
      os: 'OS: Windows 10 (Version 1909 or Newer)',
      processor: 'Processor: Intel i5-4430, AMD Ryzen 3 1200',
      memory: 'Memory: 8 GB RAM',
      graphics: 'Graphics: NVIDIA GTX 960 (4 GB), AMD R9 290X (4 GB)',
      directx: 'DirectX: Version 12',
      storage: 'Storage: 126 GB available space',
      bit1: 'Requires a 64-bit processor and operating system',
      os1: 'OS: Windows 10 (Version 1909 or Newer)',
      processor1: 'Processor: Intel i7-4770, AMD Ryzen 5 1500X',
      memory1: 'Memory: 16 GB RAM',
      graphics1: 'Graphics: NVIDIA GTX 1060 (6 GB), AMD RX 570 (4 GB)',
      directx1: 'DirectX: Version 12',
      storage1: 'Storage: 126 GB available space',
      trending: true,
    },
    {
      id: 3,
      name: "Marvel's Spider-Man Remastered",
      category: 'adventure',
      thumbnail: './assets/images/spidercard.jpg',
      image: './assets/images/spider.jpg',
      video: 'https://www.youtube.com/embed/mrT5q5xXb7Y',
      description:
        "Developed by Insomniac Games in collaboration with Marvel, and optimized for PC by Nixxes Software, Marvel's Spider-Man Remastered on PC introduces an experienced Peter Parker who’s fighting big crime and iconic villains in Marvel’s New York. At the same time, he’s struggling to balance his chaotic personal life and career while the fate of Marvel’s New York rests upon his shoulders.",
      screenshot1: './assets/images/spidershot.jpg',
      buy: "Buy Marvel's Spider-Man Remastered",

      des: 'Feel what it’s like to play as Spider-Man through immersive haptic feedback and dynamic trigger effects using a PlayStation DualSense™ controller on a wired USB connection. Enjoy full mouse and keyboard support with various customizable control options.',
      price: '₹ 3,999',
      bit: 'Requires a 64-bit processor and operating system',
      os: 'OS: Windows 10 (Version 1909 or Newer)',
      processor: 'Processor: Intel Core i3-4160, 3.6 GHz or AMD equivalent',
      memory: 'Memory: 8 GB RAM',
      graphics: 'Graphics: NVIDIA GTX 950 or AMD Radeon RX 470',
      directx: 'DirectX: Version 12',
      storage: 'Storage: 75 GB available space',
      bit1: 'Requires a 64-bit processor and operating system',
      os1: 'OS: Windows 10 (Version 1909 or Newer)',
      processor1:
        'Processor: Intel Core i5-4670, 3.4 Ghz or AMD Ryzen5 1600, 3.2 Ghz',
      memory1: 'Memory: 16 GB RAM',
      graphics1: 'Graphics: NVIDIA GTX 1060 6GB or AMD Radeon RX 580 8GB',
      directx1: 'DirectX: Version 12',
      storage1: 'Storage: 75 GB available space',
    },
    {
      id: 4,
      name: 'Grand Theft Auto V',
      category: 'adventure',
      thumbnail: './assets/images/gtacard.jpg',
      image: './assets/images/gta.jpg',
      video: 'https://www.youtube.com/embed/qoytS3930aY',
      description:
        'When a young street hustler, a retired bank robber and a terrifying psychopath find themselves entangled with some of the most frightening and deranged elements of the criminal underworld, the U.S. government and the entertainment industry, they must pull off a series of dangerous heists to survive in a ruthless city in which they can trust nobody, least of all each other.',
      screenshot1: './assets/images/gtashot.jpg',
      buy: 'Buy GTA V',
      des: 'The game offers players a huge range of PC-specific customization options, including over 25 separate configurable settings for texture quality, shaders, tessellation, anti-aliasing and more, as well as support and extensive customization for mouse and keyboard controls. Additional options include a population density slider to control car and pedestrian traffic, as well as dual and triple monitor support, 3D compatibility, and plug-and-play controller support.',
      price: '₹ 1,978',
      bit: 'Requires a 64-bit processor and operating system',
      os: 'OS: Windows 10 64 Bit, Windows 8.1 64 Bit,Windows 8 64 Bit, Windows 7 64 Bit Service Pack 1',
      processor:
        'Processor: Intel Core 2 Quad CPU Q6600 @ 2.40GHz (4 CPUs) / AMD Phenom 9850 Quad-Core Processor (4 CPUs) @ 2.5GHz',
      memory: 'Memory: 4 GB RAM',
      graphics:
        'Graphics: NVIDIA 9800 GT 1GB / AMD HD 4870 1GB (DX 10, 10.1, 11)',
      storage: 'Storage: 72 GB available space',
      bit1: 'Requires a 64-bit processor and operating system',
      os1: 'OS: Windows 10 64 Bit, Windows 8.1 64 Bit,Windows 8 64 Bit, Windows 7 64 Bit Service Pack 1',
      processor1:
        'Processor: Intel Core i5 3470 @ 3.2GHz (4 CPUs) / AMD X8 FX-8350 @ 4GHz (8 CPUs)',
      memory1: 'Memory: 8 GB RAM',
      graphics1: 'Graphics: NVIDIA GTX 660 2GB / AMD HD 7870 2GB',
      storage1: 'Storage: 72 GB available space',
    },
    {
      id: 5,
      name: 'Forza Horizon 5',
      category: 'adventure',
      thumbnail: './assets/images/forzacard.jpg',
      image: './assets/images/forza.jpg',
      video: 'https://www.youtube.com/embed/Rv7xLt5yNsM',
      description:
        'Your Ultimate Horizon Adventure awaits! Explore the vibrant and ever-evolving open world landscapes of Mexico with limitless, fun driving action in hundreds of the world’s greatest cars.',
      screenshot1: './assets/images/forzashot.jpg',
      buy: 'Buy Forza Horizon 5',
      des: 'Create your own expressions of fun with the powerful new EventLab gameplay toolset including custom races, challenges, stunts, and entirely new game modes. Customize your cars in more ways than ever before with new options such as the ability open and close convertible tops, paint brake calipers, and more. Use the new Gift Drops feature to share your custom creations with the community.',
      price: '₹ 3,499',
      bit: 'Requires a 64-bit processor and operating system',
      os: 'OS: Windows 10 version 15063.0 or higher',
      processor: 'Processor: Intel i5-4460 or AMD Ryzen 3 1200',
      memory: 'Memory: 8 GB RAM',
      graphics: 'Graphics: NVidia GTX 970 OR AMD RX 470',
      directx: 'DirectX: Version 12',
      network: 'Network: Broadband Internet connection',
      storage: 'Storage: 110 GB available space',
      bit1: 'Requires a 64-bit processor and operating system',
      os1: 'OS: Windows 10 version 15063.0 or higher',
      processor1: 'Processor: Intel i5-8400 or AMD Ryzen 5 1500X',
      memory1: 'Memory: 16 GB RAM',
      graphics1: 'Graphics: NVidia GTX 1070 OR AMD RX 590',
      directx1: 'DirectX: Version 12',
      network1: 'Network: Broadband Internet connection',
      storage1: 'Storage: 110 GB available space',
    },
    {
      id: 6,
      name: 'The Witcher 3 Wild Hunt',
      category: 'adventure',
      thumbnail: './assets/images/witchercard.jpg',
      image: './assets/images/witcher.jpg',
      video: 'https://www.youtube.com/embed/XHrskkHf958',
      description:
        'You are Geralt of Rivia, mercenary monster slayer. Before you stands a war-torn, monster-infested continent you can explore at will. Your current contract? Tracking down Ciri — the Child of Prophecy, a living weapon that can alter the shape of the world. Updated to the latest version, The Witcher 3: Wild Hunt comes with new features and items, including a built-in Photo Mode, swords, armor, and alternate outfits inspired by The Witcher Netflix series — and more!',
      screenshot1: './assets/images/witchershot.jpg',
      buy: 'Buy The Witcher 3 Wild Hunt',
      des: 'Trained from early childhood and mutated to gain superhuman skills, strength, and reflexes, witchers are a counterbalance to the monster-infested world in which they live. • Gruesomely destroy foes as a professional monster hunter armed with a range of upgradeable weapons, mutating potions, and combat magic. • Hunt down a wide variety of exotic monsters, from savage beasts prowling mountain passes to cunning supernatural predators lurking in the shadowy back alleys of densely populated cities. • Invest your rewards to upgrade your weaponry and buy custom armor, or spend them on horse races, card games, fist fighting, and other pleasures life brings.',
      price: '₹ 800',
      bit: 'Requires a 64-bit processor and operating system',
      os: 'OS: 64-bit Windows 7, 64-bit Windows 8 (8.1)',
      processor:
        'Processor: Intel CPU Core i5-2500K 3.3GHz / AMD A10-5800K APU (3.8GHz)',
      memory: 'Memory: 6 GB RAM',
      graphics: 'Graphics: Nvidia GPU GeForce GTX 660 / AMD GPU',
      directx: 'DirectX: Version 11',
      storage: 'Storage: 50 GB available space',
      bit1: 'Requires a 64-bit processor and operating system',
      os1: 'OS: 64-bit Windows 10/11',
      processor1: 'Processor: Intel Core i5-7400 / Ryzen 5 1600',
      memory1: 'Memory: 8 GB RAM',
      graphics1: 'Graphics: Nvidia GTX 1070 / Radeon RX 480',
      directx1: 'DirectX: Version 12',
      storage1: 'Storage: 50 GB available space',
    },
    {
      id: 7,
      name: 'Resident Evil 4',
      category: 'adventure',
      thumbnail: './assets/images/residentcard.jpg',
      image: './assets/images/resident.jpg',
      video: 'https://www.youtube.com/embed/Id2EaldBaWw',
      description:
        "Survival is just the beginning. Six years have passed since the biological disaster in Raccoon City. Agent Leon S. Kennedy, one of the survivors of the incident, has been sent to rescue the president's kidnapped daughter He tracks her to a secluded European village, where there is something terribly wrong with the locals. And the curtain rises on this story of daring rescue and grueling horror where life and death, terror and catharsis intersect. Featuring modernized gameplay, a reimagined storyline, and vividly detailed graphics, Resident Evil 4 marks the rebirth of an industry juggernaut. Relive the nightmare that revolutionized survival horror.",
      screenshot1: './assets/images/residentshot.jpg',
      buy: 'Buy Resident Evil 4',
      des: 'The developers describe the content like this: This Game may contain content not appropriate for all ages, or may not be appropriate for viewing at work: Frequent Violence or Gore, General Mature Content',
      price: '₹ 3,599',
      bit: 'Requires a 64-bit processor and operating system',
      os: 'OS: Windows 10 (64 bit)',
      processor: 'Processor: AMD Ryzen 3 1200 / Intel Core i5-7500',
      memory: 'Memory: 8 GB RAM',
      graphics:
        'Graphics: AMD Radeon RX 560 with 4GB VRAM / NVIDIA GeForce GTX 1050 Ti with 4GB VRAM',
      directx: 'DirectX: Version 12',
      network: 'Network: Broadband Internet connection',
      notes:
        'Additional Notes: Estimated performance (when set to Prioritize Performance): 1080p/45fps. ・Framerate might drop in graphics-intensive scenes. ・AMD Radeon RX 6700 XT or NVIDIA GeForce RTX 2060 required to support ray tracing.',
      bit1: 'Requires a 64-bit processor and operating system',
      os1: 'OS: Windows 10 (64 bit)/Windows 11 (64 bit)',
      processor1: 'Processor: AMD Ryzen 5 3600 / Intel Core i7 8700',
      memory1: 'Memory: 16 GB RAM',
      graphics1: 'Graphics: AMD Radeon RX 5700 / NVIDIA GeForce GTX 1070',
      directx1: 'DirectX: Version 12',
      network1: 'Network: Broadband Internet connection',
      notes1:
        'Additional Notes: Estimated performance: 1080p/60fps ・Framerate might drop in graphics-intensive scenes. ・AMD Radeon RX 6700 XT or NVIDIA GeForce RTX 2070 required to support ray tracing.',
    },
    {
      id: 8,
      name: 'Final Fantasy VII Remake Intergrade',
      category: 'adventure',
      thumbnail: './assets/images/fantasycard.jpg',
      image: './assets/images/fantasy.jpg',
      video: 'https://www.youtube.com/embed/sz9QWTcbXYE',
      description:
        'FINAL FANTASY VII REMAKE is a bold reimagining of the original FINAL FANTASY VII, originally released in 1997, developed under the guidance of the original key developers. This critically-acclaimed game, which mixes traditional command-based combat and real-time action, makes its Steam debut along with FF7R EPISODE INTERmission─a new story arc featuring Yuffie Kisaragi.',
      screenshot1: './assets/images/fantasyshot.jpg',
      buy: 'Buy Final Fantasy VII Remake Intergrade',
      des: 'By exploiting mako, the life-blood of the planet, through their mako reactors, the Shinra Electric Power Company has all but seized control of the entire world. A ragtag group of idealists, known as Avalanche, are one of the last bastions of resistance. Cloud, an elite SOLDIER operative-turned-mercenary takes part in an Avalanche operation to destroy Mako Reactor 1 in the city of Midgar. The bombing plunges the city into fiery chaos, and Cloud is tormented by visions of a bitter enemy long thought dead. Once more begins a story that will shape the destiny of an entire world. This game is a remake of FINAL FANTASY VII, first released in 1997. The first title in a multi-part series, it is based on the story from the original game, up to the escape from Midgar, adding in new elements.',
      price: '₹ 4,799',
      bit: 'Requires a 64-bit processor and operating system',
      os: 'OS: Windows® 10 64-bit (ver. 2004 or later)',
      processor: 'Processor: AMD FX-8350 / Intel® Core™ i5-3330',
      memory: 'Memory: 8 GB RAM',
      graphics:
        'Graphics: AMD Radeon™ RX 480 / NVIDIA® GeForce® GTX 780 / 3GB VRAM required',
      directx: 'DirectX: Version 12',
      storage: 'Storage: 100 GB available space',
      notes: 'Additional Notes: Assuming a Resolution of 1920 x 1080',
      bit1: 'Requires a 64-bit processor and operating system',
      os1: 'OS: Windows® 10 64-bit (ver. 2004 or later)',
      processor1: 'Processor: AMD Ryzen™ 3 3100 / Intel® Core™ i7-3770',
      memory1: 'Memory: 12 GB RAM',
      graphics1:
        'Graphics: AMD Radeon™ RX 5700 / NVIDIA® GeForce® GTX 1080 / 8GB VRAM required',
      directx1: 'DirectX: Version 12',
      storage1: 'Storage: 100 GB available space',
      notes1:
        'Additional Notes: Assuming a Resolution of 2560 x 1440 (This title supports max resolution of 3840 x 2160)',
    },
    {
      id: 9,
      name: 'Need For Speed Unbound',
      category: 'action',
      thumbnail: './assets/images/unboundcard.jpg',
      image: './assets/images/unbound.jpg',
      video: 'https://www.youtube.com/embed/YM6nUa2_EBQ',
      description:
        "The world is your canvas in Need for Speed™ Unbound. Prove you have what it takes to win The Grand, Lakeshore's ultimate street racing challenge. Across 4 intense weeks of racing, earn enough cash to enter weekly qualifiers, beat the competition, and make your mark on the street racing scene while outdriving and outsmarting the cops. Pack your garage with precision-tuned, custom rides and light up the streets with your unique style, exclusive fits, and a vibrant global soundtrack led by A$AP Rocky and AWGE that bumps in every corner of the world.",
      screenshot1: './assets/images/unboundshot.jpg',
      buy: 'Buy Need for Speed Unbound',
      price: '₹ 3,499',
      des: " Express yourself to the fullest with the freshest new art styles and signature tags that represent what you're all about. With separate single- and multiplayer campaigns, this latest edition in the Need for Speed franchise from Criterion Games™ delivers hours of electric, adrenaline-pumping action.",
      bit: 'Requires a 64-bit processor and operating system',
      os: 'OS: Windows 10 64-bit',
      processor: 'Processor: Ryzen 5 2600, Core i5-8600',
      memory: 'Memory: 8 GB RAM',
      graphics: 'Graphics: RX 570, GTX 1050 Ti',
      directx: 'DirectX: Version 12',
      network: 'Network: Broadband Internet connection',
      storage: 'Storage: 50 GB available space',
      bit1: 'Requires a 64-bit processor and operating system',
      os1: 'OS: Windows 10 64-bit',
      processor1: 'Processor: Ryzen 5 3600, Core i7-8700',
      memory1: 'Memory: 16 GB RAM',
      graphics1: 'Graphics: Radeon RX5700 (8GB), GeForce RTX 2070 (8GB)',
      directx1: 'DirectX: Version 12',
      network1: 'Network: Broadband Internet connection',
      storage1: 'Storage: 50 GB available space',
      trending: true,
    },
    {
      id: 10,
      name: 'A Plague Tale Requiem',
      category: 'action',
      thumbnail: './assets/images/plaguecard.jpg',
      image: './assets/images/plague.jpg',
      video: 'https://www.youtube.com/embed/qIbzwb8vzNI',
      description:
        'Far across the sea, an island calls… Embark on a heartrending journey into a brutal, breathtaking world twisted by supernatural forces. After escaping their devastated homeland, Amicia and Hugo travel far south, to new regions and vibrant cities. There, they attempt to start a new life and control Hugo’s curse. But, when Hugo’s powers reawaken, death and destruction return in a flood of devouring rats. Forced to flee once more, the siblings place their hopes in a prophesized island that may hold the key to saving Hugo. Discover the cost of saving those you love in a desperate struggle for survival. Strike from the shadows or unleash hell, overcoming foes and challenges with a variety of weapons, tools and unearthly powers.',
      screenshot1: './assets/images/plagueshot.jpg',
      buy: 'Buy A Plague Tale Requiem',
      des: ' Sequel to the award-winning adventure A Plague Tale: Innocence. A spectacular grounded tale twisted by supernatural forces. Use a variety of tools, sneak, fight, or unleash hell and rats. Stunning visuals combine with an enthralling score',
      price: '₹ 1,999',
      bit: 'Requires a 64-bit processor and operating system',
      os: 'OS: Windows 10 (20H1 64 bits)',
      processor:
        'Processor: Intel Core i5-4690K (3.5 GHz)/AMD FX-8300 (3.3 GHz)',
      memory: 'Memory: 16 GB RAM',
      graphics: 'Graphics: 4 GB, GeForce GTX 970/Radeon RX 590',
      directx: 'DirectX: Version 12',
      storage: 'Storage: 55 GB available space',
      notes:
        'Additional Notes: 30 FPS, 1920x1080 in low. DirectX 12 Feature Level 12 and Shader Model 6.0 are needed.',
      bit1: 'Requires a 64-bit processor and operating system',
      os1: 'OS: Windows 10 (20H1 64 bits)',
      processor1:
        'Processor: Intel Core i7-8700K (3.7 GHz) / AMD Ryzen 5 3600 (3.6 GHz)',
      memory1: 'Memory: 16 GB RAM',
      graphics1: 'Graphics: 8 GB, GeForce RTX 3070/Radeon RX 6800 XT',
      directx1: 'DirectX: Version 12',
      storage1: 'Storage: 55 GB available space',
      notes1:
        'Additional Notes: 60 FPS, 1920x1080 in ultra. SSD storage is recommended.',
      trending: true,
    },
    {
      id: 11,
      name: "Marvel's Spider-Man Miles Morales",
      category: 'action',
      thumbnail: './assets/images/milescard.jpg',
      image: './assets/images/miles.jpg',
      video: 'https://www.youtube.com/embed/hY3qiRq0yEM',
      description:
        'Following the events of Marvel’s Spider-Man Remastered, teenager Miles Morales is adjusting to his new home while following in the footsteps of his mentor, Peter Parker, as a new Spider-Man. But when a fierce power struggle threatens to destroy his new home, the aspiring hero realizes that with great power, there must also come great responsibility. To save all of Marvel’s New York, Miles must take up the mantle of Spider-Man and own it.',
      screenshot1: './assets/images/milesshot.jpg',
      buy: 'Buy Marvel’s Spider-Man Miles Morales',
      des: 'Enjoy a variety of graphics quality options to tailor to a wide range of devices, unlocked framerates, and support for other technologies including performance boosting NVIDIA DLSS 3 and NVIDIA DLSS 2, image quality enhancing NVIDIA DLAA, and latency-reducing NVIDIA Reflex. Upscaling technologies AMD FSR 2.1, Intel XeSS and IGTI are also supported.',
      price: '₹ 3,299',
      bit: 'Requires a 64-bit processor and operating system',
      os: 'OS: Windows 10 64-bit 1909',
      processor: 'Processor: Intel Core i3-4160, 3.6 GHz or AMD equivalent',
      memory: 'Memory: 8 GB RAM',
      graphics: 'Graphics: NVIDIA GTX 950 or AMD Radeon RX 470',
      directx: 'DirectX: Version 12',
      storage: 'Storage: 75 GB available space',
      bit1: 'Requires a 64-bit processor and operating system',
      os1: 'OS: Windows 10 64-bit 1909',
      processor1:
        'Processor: Intel Core i5-4670, 3.4 Ghz or AMD Ryzen 5 1600, 3.2 Ghz',
      memory1: 'Memory: 16 GB RAM',
      graphics1: 'Graphics: NVIDIA GTX 1060 6GB or AMD Radeon RX 580 8GB',
      directx1: 'DirectX: Version 12',
      storage1: 'Storage: 75 GB available space',
      notes1: 'Additional Notes: 75 GB SSD space Recommended',
    },
    {
      id: 12,
      name: 'Counter-Strike: Global Offensive',
      category: 'action',
      thumbnail: './assets/images/countercard.jpg',
      image: './assets/images/counter.jpg',
      video: 'https://www.youtube.com/embed/edYCtaNueQY',
      description:
        'Counter-Strike: Global Offensive (CS: GO) expands upon the team-based action gameplay that it pioneered when it was launched 19 years ago. CS: GO features new maps, characters, weapons, and game modes, and delivers updated versions of the classic CS content (de_dust2, etc.).',
      screenshot1: './assets/images/countershot.jpg',
      buy: 'Buy Counter-Strike: Global Offensive',
      des: "Counter-Strike took the gaming industry by surprise when the unlikely MOD became the most played online PC action game in the world almost immediately after its release in August 1999,said Doug Lombardi at Valve. For the past 12 years, it has continued to be one of the most-played games in the world, headline competitive gaming tournaments and selling over 25 million units worldwide across the franchise. CS: GO promises to expand on CS' award-winning gameplay and deliver it to gamers on the PC as well as the next gen consoles and the Mac.",
      price: '₹ 1,140',
      os: 'OS: Windows® 7/Vista/XP',
      processor:
        'Processor: Intel® Core™ 2 Duo E6600 or AMD Phenom™ X3 8750 processor or better',
      memory: 'Memory: 2 GB RAM',
      graphics:
        'Graphics: Video card must be 256 MB or more and should be a DirectX 9-compatible with support for Pixel Shader 3.0',
      directx: 'DirectX: Version 9.0c',
      storage: 'Storage: 15 GB available space',
      os1: 'OS: Windows® 7/Vista/XP',
      processor1:
        'Processor: Intel® Core™ 2 Duo E6600 or AMD Phenom™ X3 8750 processor or better',
      memory1: 'Memory: 2 GB RAM',
      graphics1:
        'Graphics: Video card must be 256 MB or more and should be a DirectX 9-compatible with support for Pixel Shader 3.0',
      directx1: 'DirectX: Version 9.0c',
      storage1: 'Storage: 15 GB available space',
    },
    {
      id: 13,
      name: 'Apex Legends',
      category: 'action',
      thumbnail: './assets/images/apexcard.jpg',
      image: './assets/images/apex.jpg',
      video: 'https://www.youtube.com/embed/innmNewjkuk',
      description:
        'Conquer with character in Apex Legends, a free-to-play* Hero shooter where legendary characters with powerful abilities team up to battle for fame & fortune on the fringes of the Frontier. Master an ever-growing roster of diverse Legends, deep-tactical squad play, and bold, new innovations that go beyond the Battle Royale experience — all within a rugged world where anything goes. Welcome to the next evolution of Hero Shooter.',
      screenshot1: './assets/images/apexshot.jpg',
      buy: 'Buy Apex Legents',
      des: 'This game includes optional in-game purchases of virtual currency that can be used to acquire virtual in-game items, including a random selection of virtual in-game items. Note that any unused Apex Coins will expire 180 days after the first date in which they are acquired or purchased. The oldest Apex Coins that are subject to expiration in your balance will always be used first when using them to make in-game purchases.',
      price: '₹ 743',
      bit: 'Requires a 64-bit processor and operating system',
      os: 'OS: 64-bit Windows 7',
      processor:
        'Processor: AMD FX 4350 or Equivalent, Intel Core i3 6300 or Equivalent',
      memory: 'Memory: 6 GB RAM',
      graphics: 'Graphics: AMD Radeon™ HD 7730, NVIDIA GeForce® GT 640',
      directx: 'DirectX: Version 11',
      network: 'Network: Broadband Internet connection',
      storage: 'Storage: 56 GB available space',
      notes: 'Additional Notes: ~3.8GB for 1 localized language',
      bit1: 'Requires a 64-bit processor and operating system',
      os1: 'OS: 64-bit Windows 7',
      processor1: 'Processor: Ryzen 5 CPU or Equivalent',
      memory1: 'Memory: 8 GB RAM',
      graphics1: 'Graphics: AMD Radeon™ R9 290, NVIDIA GeForce® GTX 970',
      directx1: 'DirectX: Version 11',
      network1: 'Network: Broadband Internet connection',
      storage1: 'Storage: 56 GB available space',
      notes1: 'Additional Notes: ~3.8GB for 1 localized language',
    },
    {
      id: 14,
      name: 'Call of Duty Modern Warfare II',
      category: 'action',
      thumbnail: './assets/images/moderncard.jpg',
      image: './assets/images/modern.jpg',
      video: 'https://www.youtube.com/embed/9rg2veTiQTw',
      description:
        'Existing Modern Warfare® II Digital Standard Edition owners can upgrade to the Vault Edition as part of a limited time offer. Welcome to the new era of Call of Duty®. Call of Duty®: Modern Warfare® II drops players into an unprecedented global conflict that features the return of the iconic Operators of Task Force 141. From small-scale, high-stakes infiltration tactical ops to highly classified missions, players will deploy alongside friends in a truly immersive experience.',
      screenshot1: './assets/images/modernshot.jpg',
      buy: 'Buy Call of Duty Modern Warfare II',
      des: 'Infinity Ward brings fans state-of-the-art gameplay, with all-new gun handling, advanced AI system, a new Gunsmith and a suite of other gameplay and graphical innovations that elevate the franchise to new heights. Modern Warfare® II launches with a globe-trotting single-player campaign, immersive Multiplayer combat and a narrative-driven, co-op Special Ops experience. You also get access to Call of Duty®: Warzone™ 2.0, the all-new Battle Royale experience.',
      price: '₹ 3,249',
      bit: 'Requires a 64-bit processor and operating system',
      os: 'OS: Windows® 10 64 Bit (latest update)',
      processor:
        'Processor: Intel® Core™ i3-6100 / Core™ i5-2500K or AMD Ryzen™ 3 1200',
      memory: 'Memory: 8 GB RAM',
      graphics: 'Graphics: NVIDIA® GeForce® GTX 960 or AMD',
      directx: 'DirectX: Version 12',
      network: 'Network: Broadband Internet connection',
      storage: 'Storage: 125 GB available space',
      bit1: 'Requires a 64-bit processor and operating system',
      os1: 'OS: Windows® 10 64 Bit (latest update) or Windows® 11 64 Bit (latest update)',
      processor1:
        'Processor: Intel® Core™ i5-6600K / Core™ i7-4770 or AMD Ryzen™ 5 1400',
      memory1: 'Memory: 12 GB RAM',
      graphics1:
        'Graphics: NVIDIA® GeForce® GTX 1060 or AMD Radeon™ RX 580 - DirectX 12.0 compatible system',
      directx1: 'DirectX: Version 12',
      network1: 'Network: Broadband Internet connection',
      storage1: 'Storage: 125 GB available space',
    },
    {
      id: 15,
      name: 'Like a Dragon:Ishin!',
      category: 'action',
      thumbnail: './assets/images/dragoncard.jpg',
      image: './assets/images/dragon.jpg',
      video: 'https://www.youtube.com/embed/8ixRs8MX4aQ',
      description:
        'Don the clothes and weaponry of the elite to become the samurai of legend, Sakamoto Ryoma. The Deluxe Edition both adds challenge to your journey and gives you additional resources to overcome it. The Deluxe Edition includes: Shinsengumi Captain’s Set Ryoma Growth Support Kit Sword Upgrade Materials Kit Gun Upgrade Materials Kit Third Division Armament Expansion Kit The Dragon of Dojima Skin',
      screenshot1: './assets/images/dragonshot.jpg',
      buy: 'Buy Like a Dragon:Ishin!',
      des: '1860s Kyo is plagued by widespread inequality, and one samurai will change the course of history in his search for justice. Take up the sword of Sakamoto Ryoma and venture to Kyoto to find your father’s killer, clear yourself of a framed murder, and restore your honor. In doing so, you will bring an end to the samurai era and forever change the future of Japan. Draw your blade, load your revolver, and join the revolution in this heated historical adventure that only the creators of Yakuza: Like a Dragon could produce.',
      price: '₹ 3,499',
      bit: 'Requires a 64-bit processor and operating system',
      os: 'OS: Windows 10',
      processor:
        'Processor: Intel Core i5-3470, 3.2 GHz or AMD Ryzen 3 1200, 3.1 GHz',
      memory: 'Memory: 8 GB RAM',
      graphics:
        'Graphics: NVIDIA GeForce GTX 960, 2 GB or AMD Radeon RX 460, 2 GB',
      directx: 'DirectX: Version 11',
      storage: 'Storage: 60 GB available space',
      notes:
        'Additional Notes: 1080p Low @ 30 FPS. Requires a CPU which supports the AVX and SSE4.2 instruction set.',
      bit1: 'Requires a 64-bit processor and operating system',
      os1: 'OS: Windows 10',
      processor1:
        'Processor: Intel Core i7-4790, 3.6 GHz or AMD Ryzen 5 1600, 3.2 GHz',
      memory1: 'Memory: 8 GB RAM',
      graphics1:
        'Graphics: NVIDIA GeForce RTX 2060, 6 GB or AMD Radeon RX Vega 56, 8 GB',
      directx1: 'DirectX: Version 12',
      storage1: 'Storage: 60 GB available space',
      notes1:
        'Additional Notes: 1080p High @ 60 FPS. Requires a CPU which supports the AVX and SSE4.2 instruction set.',
    },
    {
      id: 16,
      name: 'PUBG: Battlegrounds',
      category: 'action',
      thumbnail: './assets/images/pubgcard.jpg',
      image: './assets/images/pubg.jpg',
      video: 'https://www.youtube.com/embed/fDLAFIhfFy4',
      description:
        'LAND, LOOT, SURVIVE! Play PUBG: BATTLEGROUNDS for free. Land on strategic locations, loot weapons and supplies, and survive to become the last team standing across various, diverse Battlegrounds. Squad up and join the Battlegrounds for the original Battle Royale experience that only PUBG: BATTLEGROUNDS can offer.',
      screenshot1: './assets/images/pubgshot.jpg',
      buy: 'Buy PUBG: Battlegrounds',
      des: 'This content download will also provide access to the BATTLEGROUNDS Test Server, which requires a separate download to play. Optional in-game purchases available.',
      price: '₹ 999',
      bit: 'Requires a 64-bit processor and operating system',
      os: 'OS: 64-bit Windows 10',
      processor: 'Processor: Intel Core i5-4430 / AMD FX-6300',
      memory: 'Memory: 8 GB RAM',
      graphics: 'Graphics: NVIDIA GeForce GTX 960 2GB / AMD Radeon R7 370 2GB',
      directx: 'DirectX: Version 11',
      network: 'Network: Broadband Internet connection',
      storage: 'Storage: 40 GB available space',
      bit1: 'Requires a 64-bit processor and operating system',
      os1: 'OS: 64-bit Windows 10',
      processor1: 'Processor: Intel Core i5-6600K / AMD Ryzen 5 1600',
      memory1: 'Memory: 16 GB RAM',
      graphics1:
        'Graphics: NVIDIA GeForce GTX 1060 3GB / AMD Radeon RX 580 4GB',
      directx1: 'DirectX: Version 11',
      network1: 'Network: Broadband Internet connection',
      storage1: 'Storage: 50 GB available space',
    },
    {
      id: 17,
      name: 'Cyberpunk 2077',
      category: 'rpg',
      thumbnail: './assets/images/cybercard.jpg',
      image: './assets/images/cyber.jpg',
      video: 'https://www.youtube.com/embed/qIcTM8WXFjk',
      description:
        'Cyberpunk 2077 is an open-world, action-adventure RPG set in the megalopolis of Night City, where you play as a cyberpunk mercenary wrapped up in a do-or-die fight for survival. Improved and featuring all-new free additional content, customize your character and playstyle as you take on jobs, build a reputation, and unlock upgrades.',
      screenshot1: './assets/images/cybershot.jpg',
      buy: 'Buy Cyberpunk 2077',
      price: '₹ 2,999',
      des: ' The relationships you forge and the choices you make will shape the story and the world around you. Legends are made here. What will yours be?',
      bit: 'Requires a 64-bit processor and operating system',
      os: 'OS: Windows 10',
      processor: 'Processor: Intel Core i5-3570K or AMD FX-8310',
      memory: 'Memory: 8 GB RAM',
      graphics: 'Graphics: NVIDIA GeForce GTX 970 or AMD Radeon RX 470',
      directx: 'DirectX: Version 12',
      storage: 'Storage: 70 GB available space',
      notes:
        'Additional Notes: In this game you will encounter a variety of visual effects that may provide seizures or loss of consciousness in a minority of people. If you or someone you know experiences any of the above symptoms while playing, stop and seek medical attention immediately.',
      bit1: 'Requires a 64-bit processor and operating system',
      os1: 'OS: Windows 10',
      processor1: 'Processor: Intel Core i7-4790 or AMD Ryzen 3 3200G',
      memory1: 'Memory: 12 GB RAM',
      graphics1: 'Graphics: GTX 1060 6GB / GTX 1660 Super or Radeon RX 590',
      directx1: 'DirectX: Version 12',
      storage1: 'Storage: 70 GB available space',
      notes1: 'Additional Notes: SSD recommended',
      trending: true,
    },
    {
      id: 18,
      name: 'Hogwarts Legacy',
      category: 'rpg',
      thumbnail: './assets/images/hogcard.jpg',
      image: './assets/images/hog.jpg',
      video: 'https://www.youtube.com/embed/BtyBjOW8sGY',
      description:
        'Hogwarts Legacy is an open-world action RPG set in the world first introduced in the Harry Potter books. Embark on a journey through familiar and new locations as you explore and discover magical beasts, customize your character and craft potions, master spell casting, upgrade talents and become the wizard you want to be.',
      screenshot1: './assets/images/hogshot.jpg',
      buy: 'Buy Hogwarts Legacy',
      des: 'Experience Hogwarts in the 1800s. Your character is a student who holds the key to an ancient secret that threatens to tear the wizarding world apart. Make allies, battle Dark wizards, and ultimately decide the fate of the wizarding world. Your legacy is what you make of it. Live the Unwritten.',
      price: '₹ 2,999',
      bit: 'Requires a 64-bit processor and operating system',
      os: 'OS: 64-bit Windows 10',
      processor:
        'Processor: Intel Core i5-6600 (3.3Ghz) or AMD Ryzen 5 1400 (3.2Ghz)',
      memory: 'Memory: 16 GB RAM',
      graphics: 'Graphics: NVIDIA GeForce GTX 960 4GB or AMD Radeon RX 470 4GB',
      directx: 'DirectX: Version 12',
      storage: 'Storage: 85 GB available space',
      notes:
        'Additional Notes: SSD (Preferred), HDD (Supported), 720p/30 fps, Low Quality Settings',
      bit1: 'Requires a 64-bit processor and operating system',
      os1: 'OS: 64-bit Windows 10',
      processor1:
        'Processor: Intel Core i7-8700 (3.2Ghz) or AMD Ryzen 5 3600 (3.6 Ghz)',
      memory1: 'Memory: 16 GB RAM',
      graphics1:
        'Graphics: NVIDIA GeForce 1080 Ti or AMD Radeon RX 5700 XT or INTEL Arc A770',
      directx1: 'DirectX: Version 12',
      storage1: 'Storage: 85 GB available space',
      notes1: 'Additional Notes: SSD, 1080p/60 fps, High Quality Settings',
      trending: true,
    },
    {
      id: 19,
      name: 'God of War',
      category: 'rpg',
      thumbnail: './assets/images/godcard.jpg',
      image: './assets/images/god.jpg',
      video: 'https://www.youtube.com/embed/HqQMh_tij0c',
      description:
        'His vengeance against the Gods of Olympus years behind him, Kratos now lives as a man in the realm of Norse Gods and monsters. It is in this harsh, unforgiving world that he must fight to survive… and teach his son to do the same.Kratos is a father again. As mentor and protector to Atreus, a son determined to earn his respect, he is forced to deal with and control the rage that has long defined him while out in a very dangerous world with his son.',
      screenshot1: './assets/images/godshot.jpg',
      buy: 'Buy God of War',
      des: 'With an over the shoulder camera that brings the player closer to the action than ever before, fights in God of War™ mirror the pantheon of Norse creatures Kratos will face: grand, gritty and grueling. A new main weapon and new abilities retain the defining spirit of the God of War series while presenting a vision of conflict that forges new ground in the genre.',
      price: '₹ 3,299',
      bit: 'Requires a 64-bit processor and operating system',
      os: 'OS: 64-bit Windows 10',
      processor:
        'Processor: Intel i5-2500k (4 core 3.3 GHz) or AMD Ryzen 3 1200 (4 core 3.1 GHz)',
      memory: 'Memory: 8 GB RAM',
      graphics: 'Graphics: NVIDIA GTX 960 (4 GB) or AMD R9 290X (4 GB)',
      directx: 'DirectX: Version 11',
      storage: 'Storage: 70 GB available space',
      notes: 'Additional Notes: DirectX feature level 11_1 required',
      bit1: 'Requires a 64-bit processor and operating system',
      os1: 'OS: 64-bit Windows 10',
      processor1:
        'Processor: Intel i5-6600k (4 core 3.5 GHz) or AMD Ryzen 5 2400 G (4 core 3.6 GHz)',
      memory1: 'Memory: 8 GB RAM',
      graphics1: 'Graphics: NVIDIA GTX 1060 (6 GB) or AMD RX 570 (4 GB)',
      directx1: 'DirectX: Version 11',
      storage1: 'Storage: 70 GB available space',
      notes1: 'Additional Notes: DirectX feature level 11_1 required',
    },
    {
      id: 20,
      name: 'Gotham Knights',
      category: 'rpg',
      thumbnail: './assets/images/gothamcard.jpg',
      image: './assets/images/gotham.jpg',
      video: 'https://www.youtube.com/embed/CbyT8nvn5Mc',
      description:
        'Batman is dead. A new expansive, criminal underworld has swept the streets of Gotham City. It is now up to the Batman Family - Batgirl, Nightwing, Red Hood, and Robin - to protect Gotham, bring hope to its citizens, discipline to its cops, and fear to its criminals. From solving mysteries that connect the darkest chapters in the city’s history to defeating notorious villains in epic confrontations.',
      screenshot1: './assets/images/gothamshot.jpg',
      buy: 'Buy Gotham Knights',
      des: 'Gotham Knights is an open-world, action RPG set in the most dynamic and interactive Gotham City yet. Patrol Gotham’s five distinct boroughs in solo or in co-op and drop in on criminal activity wherever you find it. Your legacy begins now. Step into the Knight.',
      price: '₹ 2,999',
      bit: 'Requires a 64-bit processor and operating system',
      os: 'OS: 64-bit Windows 10',
      processor:
        'Processor: Intel Core i5-9600K (3.7 GHz) OR AMD Ryzen 5 3600 (3.60 GHz)',
      memory: 'Memory: 8 GB RAM',
      graphics: 'Graphics: NVIDIA GeForce GTX 1660 Ti OR AMD Radeon RX 590',
      directx: 'DirectX: Version 12',
      storage: 'Storage: 45 GB available space',
      notes: 'Additional Notes: 1080p / 60fps / Low Quality Settings',
      bit1: 'Requires a 64-bit processor and operating system',
      os1: 'OS: 64-bit Windows 10',
      processor1:
        'Processor: Intel Core i7-10700K (3.8 GHz) or AMD Ryzen 5 5600X (3.7 GHz)',
      memory1: 'Memory: 16 GB RAM',
      graphics1: 'Graphics: NVIDIA GeForce RTX 2070 or AMD Radeon RX 5700 XT',
      directx1: 'DirectX: Version 12',
      storage1: 'Storage: 45 GB available space',
      notes1: 'Additional Notes: 1080p / 60fps / High Quality Settings',
    },
    {
      id: 21,
      name: 'Elden Ring',
      category: 'rpg',
      thumbnail: './assets/images/eldencard.jpg',
      image: './assets/images/elden.jpg',
      video: 'https://www.youtube.com/embed/AKXiKBnzpBQ',
      description:
        'THE NEW FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.',
      screenshot1: './assets/images/eldenshot.jpg',
      buy: 'Buy Elden Ring',
      des: 'A vast world where open fields with a variety of situations and huge dungeons with complex and three-dimensional designs are seamlessly connected. As you explore, the joy of discovering unknown and overwhelming threats await you, leading to a high sense of accomplishment.',
      price: '₹ 2,499',
      bit: 'Requires a 64-bit processor and operating system',
      os: 'OS: Windows 10',
      processor: 'Processor: INTEL CORE I5-8400 or AMD RYZEN 3 3300X',
      memory: 'Memory: 12 GB RAM',
      graphics:
        'Graphics: NVIDIA GEFORCE GTX 1060 3 GB or AMD RADEON RX 580 4 GB',
      directx: 'DirectX: Version 12',
      storage: 'Storage: 60 GB available space',
      bit1: 'Requires a 64-bit processor and operating system',
      os1: 'OS: Windows 10/11',
      processor1: 'Processor: INTEL CORE I7-8700K or AMD RYZEN 5 3600X',
      memory1: 'Memory: 16 GB RAM',
      graphics1:
        'Graphics: NVIDIA GEFORCE GTX 1070 8 GB or AMD RADEON RX VEGA 56 8 GB',
      directx1: 'DirectX: Version 12',
      storage1: 'Storage: 60 GB available space',
    },
    {
      id: 22,
      name: 'Fallout 76',
      category: 'rpg',
      thumbnail: './assets/images/fallcard.jpg',
      image: './assets/images/fall.jpg',
      video: 'https://www.youtube.com/embed/M9FGaan35s0',
      description:
        'Bethesda Game Studios, the award-winning creators of Skyrim and Fallout 4, welcome you to Fallout 76. Twenty-five years after the bombs fell, you and your fellow Vault Dwellers—chosen from the nation’s best and brightest – emerge into post-nuclear America on Reclamation Day, 2102. Play solo or join together as you explore, quest, build, and triumph against the wasteland’s greatest threats. Explore a vast wasteland, devastated by nuclear war, in this open-world multiplayer addition to the Fallout story. Experience the largest, most dynamic world ever created in the legendary Fallout universe.',
      screenshot1: './assets/images/fallshot.jpg',
      buy: 'Buy Fallout 76',
      des: "The Mutation Invasion is here and mutations from Daily Ops' missions have infected Public Events! Play a Mutated Public Event every hour for additional rewards and challenges, and jump back into Daily Ops to earn scaling rewards and experience a new variety of locations, enemies, and mutations.",
      price: '₹ 2,499',
      bit: 'Requires a 64-bit processor and operating system',
      os: 'OS: Windows 8.1/10 (64-bit versions)',
      processor:
        'Processor: Intel Core i5-6600k 3.5 GHz /AMD Ryzen 3 1300X 3.5 GHz or equivalent',
      memory: 'Memory: 8 GB RAM',
      graphics:
        'Graphics: NVIDIA GTX 780 3GB /AMD Radeon R9 285 2GB or equivalent',
      network: 'Network: Broadband Internet connection',
      storage: 'Storage: 80 GB available space',
      bit1: 'Requires a 64-bit processor and operating system',
      os1: 'OS: Windows 8.1/10 (64-bit versions)',
      processor1:
        'Processor: Intel Core i7-4790 3.6 GHz /AMD Ryzen 5 1500X 3.5 GHz',
      memory1: 'Memory: 8 GB RAM',
      graphics1: 'Graphics: NVIDIA GTX 970 4GB /AMD R9 290X 4GB',
      network1: 'Network: Broadband Internet connection',
      storage1: 'Storage: 80 GB available space',
    },
    {
      id: 23,
      name: "Marvel's Midnight Suns",
      category: 'rpg',
      thumbnail: './assets/images/midnightcard.jpg',
      image: './assets/images/midnight.jpg',
      video: 'https://www.youtube.com/embed/kTHMbNo4-n8',
      description:
        'Marvel’s Midnight Suns is the ultimate crossover event combining the rich story, character relationships, customization and progression of an RPG with the tactical strategy and combat mechanics of a revolutionary new card-based tactics game. Set in the darker side of the Marvel Universe, you will forge unbreakable bonds with legendary Marvel Super Heroes and dangerous supernatural warriors in the fight against the world’s greatest threat yet…the demonic forces of Lilith and the elder god Chthon.',
      screenshot1: './assets/images/midnightshot.jpg',
      buy: "Buy Marvel's Midnight Suns",
      des: 'You are the Hunter, the first fully-customizable original hero in the Marvel Universe. Personalize your appearance, choose your reactions to situations, and build friendships with Marvel legends spanning The Avengers, X-Men, Runaways, and more. Decide who to take with you on missions, which missions to embark on, and a host of other options to make this a unique experience.',
      price: '₹ 2,039',
      bit: 'Requires a 64-bit processor and operating system',
      os: 'OS: Windows 10 64-bit',
      processor: 'Processor: AMD Ryzen 3-2200G / Intel Core i5-4430',
      memory: 'Memory: 8 GB RAM',
      graphics: 'Graphics: AMD RX 470 / GeForce GTX 960 - 4GB',
      directx: 'DirectX: Version 12',
      storage: 'Storage: 60 GB available space',
      bit1: 'Requires a 64-bit processor and operating system',
      os1: 'OS: Windows 10 64-bit',
      processor1: 'Processor: AMD Ryzen 5-2600X / Intel Core i7-6700',
      memory1: 'Memory: 16 GB RAM',
      graphics1: 'Graphics: AMD RX 5700 / GeForce GTX 1070',
      directx1: 'DirectX: Version 12',
      storage1: 'Storage: 60 GB available space',
    },
    {
      id: 24,
      name: 'Borderlands 3',
      category: 'rpg',
      thumbnail: './assets/images/bordercard.jpg',
      image: './assets/images/border.jpg',
      video: 'https://www.youtube.com/embed/PINqlmk8xXE',
      description:
        'The original shooter-looter returns, packing bazillions of guns and an all-new mayhem-fueled adventure! Blast through new worlds and enemies as one of four brand new Vault Hunters – the ultimate treasure-seeking badasses of the Borderlands, each with deep skill trees, abilities, and customization. Play solo or join with friends to take on insane enemies, score loads of loot and save your home from the most ruthless cult leaders in the galaxy.',
      screenshot1: './assets/images/bordershot.jpg',
      buy: 'Buy Borderlands 3',
      des: 'With bazillions of guns and gadgets, every fight is an opportunity to score new gear. Firearms with self-propelling bullet shields? Check. Rifles that spawn fire-spewing volcanoes? Obviously. Guns that grow legs and chase down enemies while hurling verbal insults? Yeah, got that too.',
      price: '₹ 2,990',
      bit: 'Requires a 64-bit processor and operating system',
      os: 'OS: Windows 7/10 (latest service pack)',
      processor: 'Processor: AMD FX-8350 or Intel i5-3570',
      memory: 'Memory: 6 GB RAM',
      graphics: 'Graphics: AMD Radeon™ HD 7970 or NVIDIA GeForce GTX 680 2 GB',
      directx: 'DirectX: Version 11',
      storage: 'Storage: 75 GB available space',
      bit1: 'Requires a 64-bit processor and operating system',
      os1: 'OS: Windows 7/10 (latest service pack)',
      processor1: 'Processor: AMD Ryzen™ 5 2600 (Intel i7-4770)',
      memory1: 'Memory: 16 GB RAM',
      graphics1: 'Graphics: AMD Radeon™ RX 590 or NVIDIA GeForce GTX 1060 6GB',
      directx1: 'DirectX: Version 12',
      storage1: 'Storage: 75 GB available space',
    },
  ],
};
